"""add social_links and AI visual fields

Revision ID: 336e87389d8d
Revises: 924424811da0
Create Date: 2026-01-25 08:31:14.852942

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '336e87389d8d'
down_revision = '924424811da0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ai_news_stories', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image_url', sa.String(length=2000), nullable=True))
        batch_op.add_column(sa.Column('emoji', sa.String(length=10), nullable=True))

    with op.batch_alter_table('ai_research_papers', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image_url', sa.String(length=2000), nullable=True))
        batch_op.add_column(sa.Column('emoji', sa.String(length=10), nullable=True))

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('social_links', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('social_links')

    with op.batch_alter_table('ai_research_papers', schema=None) as batch_op:
        batch_op.drop_column('emoji')
        batch_op.drop_column('image_url')

    with op.batch_alter_table('ai_news_stories', schema=None) as batch_op:
        batch_op.drop_column('emoji')
        batch_op.drop_column('image_url')

    # ### end Alembic commands ###
