"""add notifications resumes event_attendance tables and new columns

Revision ID: 5b4866388cd0
Revises: 60ae66ce1d4d
Create Date: 2026-03-08 21:01:44.428360

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5b4866388cd0'
down_revision = '60ae66ce1d4d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('events', schema=None) as batch_op:
        batch_op.add_column(sa.Column('attendance_token', sa.String(length=64), nullable=True))
        batch_op.create_index(batch_op.f('ix_events_attendance_token'), ['attendance_token'], unique=True)

    with op.batch_alter_table('speakers', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tags', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('speakers', schema=None) as batch_op:
        batch_op.drop_column('tags')

    with op.batch_alter_table('events', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_events_attendance_token'))
        batch_op.drop_column('attendance_token')

    # ### end Alembic commands ###
