"""Add banner columns to user and university

Revision ID: 924424811da0
Revises: ef112b7fb42b
Create Date: 2026-01-15 18:00:25.418771

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '924424811da0'
down_revision = 'ef112b7fb42b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('universities', schema=None) as batch_op:
        batch_op.add_column(sa.Column('banner', sa.LargeBinary(), nullable=True))
        batch_op.add_column(sa.Column('banner_filename', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('banner_mimetype', sa.String(length=100), nullable=True))

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('banner_image', sa.LargeBinary(), nullable=True))
        batch_op.add_column(sa.Column('banner_image_filename', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('banner_image_mimetype', sa.String(length=100), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('banner_image_mimetype')
        batch_op.drop_column('banner_image_filename')
        batch_op.drop_column('banner_image')

    with op.batch_alter_table('universities', schema=None) as batch_op:
        batch_op.drop_column('banner_mimetype')
        batch_op.drop_column('banner_filename')
        batch_op.drop_column('banner')

    # ### end Alembic commands ###
