"""Migrate to many-to-many university relationships

Revision ID: e0e643fdaddf
Revises: 
Create Date: 2025-12-29 20:28:33.493880

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e0e643fdaddf'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('notes', sa.Column('university_only', sa.Boolean(), nullable=True))
    op.add_column('universities', sa.Column('website_url', sa.String(length=500), nullable=True))
    op.drop_constraint('university_requests_account_creation_token_key', 'university_requests', type_='unique')
    op.drop_index('ix_university_requests_account_creation_token', table_name='university_requests')
    op.create_index(op.f('ix_university_requests_account_creation_token'), 'university_requests', ['account_creation_token'], unique=True)
    op.drop_constraint('university_roles_user_id_fkey', 'university_roles', type_='foreignkey')
    op.drop_constraint('university_roles_university_id_fkey', 'university_roles', type_='foreignkey')
    op.create_foreign_key(None, 'university_roles', 'universities', ['university_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'university_roles', 'user', ['user_id'], ['id'], ondelete='CASCADE')
    op.alter_column('user', 'profile_picture_filename',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.String(length=100),
               existing_nullable=True)
    op.alter_column('user', 'profile_picture_mimetype',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=50),
               existing_nullable=True)
    op.drop_constraint('user_username_key', 'user', type_='unique')
    op.drop_column('user', 'liked_notes')
    op.drop_column('user', 'liked_universities')
    op.drop_column('user', 'username')
    op.drop_column('user', 'bookmarked_notes')
    op.drop_constraint('user_follows_follower_id_following_id_key', 'user_follows', type_='unique')
    op.create_index('ix_user_follows_follower', 'user_follows', ['follower_id'], unique=False)
    op.create_index('ix_user_follows_following', 'user_follows', ['following_id'], unique=False)
    op.create_unique_constraint('uq_user_follows', 'user_follows', ['follower_id', 'following_id'])
    op.drop_constraint('user_follows_follower_id_fkey', 'user_follows', type_='foreignkey')
    op.drop_constraint('user_follows_following_id_fkey', 'user_follows', type_='foreignkey')
    op.create_foreign_key(None, 'user_follows', 'user', ['follower_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'user_follows', 'user', ['following_id'], ['id'], ondelete='CASCADE')
    op.alter_column('user_liked_universities', 'university_id',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.Integer(),
               existing_nullable=False)
    op.drop_constraint('user_liked_universities_user_id_university_id_key', 'user_liked_universities', type_='unique')
    op.create_index('ix_user_liked_universities_university', 'user_liked_universities', ['university_id'], unique=False)
    op.create_index('ix_user_liked_universities_user', 'user_liked_universities', ['user_id'], unique=False)
    op.create_unique_constraint('uq_user_liked_university', 'user_liked_universities', ['user_id', 'university_id'])
    op.drop_constraint('user_liked_universities_user_id_fkey', 'user_liked_universities', type_='foreignkey')
    op.create_foreign_key(None, 'user_liked_universities', 'user', ['user_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'user_liked_universities', 'universities', ['university_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user_liked_universities', type_='foreignkey')
    op.drop_constraint(None, 'user_liked_universities', type_='foreignkey')
    op.create_foreign_key('user_liked_universities_user_id_fkey', 'user_liked_universities', 'user', ['user_id'], ['id'])
    op.drop_constraint('uq_user_liked_university', 'user_liked_universities', type_='unique')
    op.drop_index('ix_user_liked_universities_user', table_name='user_liked_universities')
    op.drop_index('ix_user_liked_universities_university', table_name='user_liked_universities')
    op.create_unique_constraint('user_liked_universities_user_id_university_id_key', 'user_liked_universities', ['user_id', 'university_id'])
    op.alter_column('user_liked_universities', 'university_id',
               existing_type=sa.Integer(),
               type_=sa.VARCHAR(length=100),
               existing_nullable=False)
    op.drop_constraint(None, 'user_follows', type_='foreignkey')
    op.drop_constraint(None, 'user_follows', type_='foreignkey')
    op.create_foreign_key('user_follows_following_id_fkey', 'user_follows', 'user', ['following_id'], ['id'])
    op.create_foreign_key('user_follows_follower_id_fkey', 'user_follows', 'user', ['follower_id'], ['id'])
    op.drop_constraint('uq_user_follows', 'user_follows', type_='unique')
    op.drop_index('ix_user_follows_following', table_name='user_follows')
    op.drop_index('ix_user_follows_follower', table_name='user_follows')
    op.create_unique_constraint('user_follows_follower_id_following_id_key', 'user_follows', ['follower_id', 'following_id'])
    op.add_column('user', sa.Column('bookmarked_notes', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('user', sa.Column('username', sa.VARCHAR(length=80), autoincrement=False, nullable=True))
    op.add_column('user', sa.Column('liked_universities', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('user', sa.Column('liked_notes', sa.TEXT(), autoincrement=False, nullable=True))
    op.create_unique_constraint('user_username_key', 'user', ['username'])
    op.alter_column('user', 'profile_picture_mimetype',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=100),
               existing_nullable=True)
    op.alter_column('user', 'profile_picture_filename',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=255),
               existing_nullable=True)
    op.drop_constraint(None, 'university_roles', type_='foreignkey')
    op.drop_constraint(None, 'university_roles', type_='foreignkey')
    op.create_foreign_key('university_roles_university_id_fkey', 'university_roles', 'universities', ['university_id'], ['id'])
    op.create_foreign_key('university_roles_user_id_fkey', 'university_roles', 'user', ['user_id'], ['id'])
    op.drop_index(op.f('ix_university_requests_account_creation_token'), table_name='university_requests')
    op.create_index('ix_university_requests_account_creation_token', 'university_requests', ['account_creation_token'], unique=False)
    op.create_unique_constraint('university_requests_account_creation_token_key', 'university_requests', ['account_creation_token'])
    op.drop_column('universities', 'website_url')
    op.drop_column('notes', 'university_only')
    # ### end Alembic commands ###
