"""added fields to university model

Revision ID: ef112b7fb42b
Revises: e0e643fdaddf
Create Date: 2026-01-15 16:53:40.685042

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ef112b7fb42b'
down_revision = 'e0e643fdaddf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('universities', sa.Column('social_links', sa.Text(), nullable=True))
    op.add_column('universities', sa.Column('logo', sa.LargeBinary(), nullable=True))
    op.add_column('universities', sa.Column('logo_filename', sa.String(length=255), nullable=True))
    op.add_column('universities', sa.Column('logo_mimetype', sa.String(length=100), nullable=True))
    op.add_column('university_requests', sa.Column('social_links', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('university_requests', 'social_links')
    op.drop_column('universities', 'logo_mimetype')
    op.drop_column('universities', 'logo_filename')
    op.drop_column('universities', 'logo')
    op.drop_column('universities', 'social_links')
    # ### end Alembic commands ###
